version: '3.1'

services:
  zoo1:
    container_name: zookeeper-leader
    image: zookeeper
    restart: always
    hostname: zookeeper-leader
    ports:
      - 2181:2181
    # environment:
      # ZOO_MY_ID: 1
      # ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  kafka :
    container_name: kafka-keyog
    image: wurstmeister/kafka:2.12-2.3.0
    depends_on:
      - zoo1
      # - zoo2
      # - zoo3
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "test_topic:1:1" # Topic명:Partition개수:Replica개수
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-leader:2181
      KAFKA_HEAP_OPTS: "-Xmx500M -Xms500M"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # zoo2:
  #   container_name: zookeeper-follower1
  #   image: zookeeper
  #   restart: always
  #   hostname: zoo2
  #   ports:
  #     - 2182:2181
  #   environment:
  #     ZOO_MY_ID: 2
  #     ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181

  # zoo3:
  #   container_name: zookeeper-follower2
  #   image: zookeeper
  #   restart: always
  #   hostname: zoo3
  #   ports:
  #     - 2183:2181
  #   environment:
  #     ZOO_MY_ID: 3
  #     ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181